/**
 * Webview SSR 根組件
 * Webview SSR root component
 *
 * 由 `SettingsSyncPanel.getWebviewContent()` 呼叫 `renderJsxToString(App, props)` 使用，
 * 負責產生完整的 `<!DOCTYPE html>` 文件字串。
 * Used by `SettingsSyncPanel.getWebviewContent()` via `renderJsxToString(App, props)`,
 * responsible for generating the complete `<!DOCTYPE html>` document string.
 *
 * 此檔案使用 Preact automatic JSX（jsxImportSource: "preact"），不需要手動 import h。
 * This file uses Preact automatic JSX (jsxImportSource: "preact"), no need to manually import h.
 */

import { IDEListSection } from './components/IDEList';
import { ExportImportPanel } from './components/ExportImportPanel';
import { SettingsNavigation } from './components/settings/SettingsNavigation';
import { SourceIdeIndicator } from './components/ide/SourceIdeIndicator';
import { LanguageConfiguration } from './components/LanguageConfiguration';
import { SyncTab } from './components/tabs/SyncTab';
import { AllSettingsTab } from './components/tabs/AllSettingsTab';
import { SelectedTab } from './components/tabs/SelectedTab';
import {
	IIDEInfoWebview,
	IUnavailableIDEInfoWebview,
	ILanguageConfig,
	IWebviewState,
} from './types';
import { IIDEInfo } from '../../src/types';
import { EnumCssClassSelector, EnumTabName, EnumWebviewElemId } from './types/elem-const';

/** ─── 型別定義 / Type definitions ─── */

/**
 * App SSR 根組件的 Props 介面
 * Props interface for the App SSR root component
 */
export interface IAppProps
{
	/** 可用的 IDE 列表 / List of available IDEs */
	availableIDEs: IIDEInfoWebview[];
	/** 不可用的 IDE 列表（已知但未偵測到）/ List of unavailable IDEs (known but not detected) */
	unavailableIDEs: IUnavailableIDEInfoWebview[];
	/** 當前執行此擴充功能的 IDE 名稱 / Name of the IDE currently running this extension */
	currentIDEName: string;
	/** 使用者選擇的來源 IDE UUID / UUID of the user-selected source IDE */
	sourceIDEUuid: string;
	/** 語言配置物件 / Language configuration object */
	languageConfig: ILanguageConfig;
	/** 所有支援的語言列表 / List of all supported languages */
	supportedLanguages: Array<{ code: string; name: string }>;
	/** 當前生效的語言代碼 / Currently active language code */
	currentLanguage: string;
	/** 編譯後的 CSS 字串，直接注入 `<style>` 標籤 / Compiled CSS string, injected directly into `<style>` tag */
	cssContent: string;
	/** Webview 的 CSP 來源字串，用於 Content-Security-Policy meta 標籤 / Webview CSP source string, used for Content-Security-Policy meta tag */
	cspSource: string;
	/** Webview bundle 的 URI（由 VS Code Webview API 產生）/ URI of the Webview bundle (generated by VS Code Webview API) */
	webviewScriptUri: string;
	/** 注入至 `window.__INITIAL_STATE__` 的初始狀態物件 / Initial state object injected into `window.__INITIAL_STATE__` */
	initialState: IWebviewState;
}

/** ─── CSP 組件 / CSP component ─── */

/**
 * Content Security Policy (CSP) meta 標籤組件
 * Content Security Policy (CSP) meta tag component
 *
 * 直接接受 cspSource 字串，不依賴 VS Code WebviewPanel 實例。
 * 之所以內聯定義而非使用 src/webview/components/PageHead.tsx 中的版本，
 * 是因為後者需要 SettingsSyncPanel 實例才能取得 cspSource，
 * 而 App 組件設計上不應依賴 VS Code 的 Node.js API。
 *
 * Accepts cspSource string directly, without depending on VS Code WebviewPanel instance.
 * Defined inline rather than using the version in src/webview/components/PageHead.tsx
 * because that version requires a SettingsSyncPanel instance to get cspSource,
 * and the App component should not depend on VS Code's Node.js API by design.
 */
function ContentSecurityPolicy({ cspSource }: { cspSource: string })
{
	/**
	 * 組裝 CSP 策略字串
	 * Assemble the CSP policy string
	 *
	 * 各指令說明：
	 * - default-src 'none'：預設拒絕所有資源，作為最嚴格的基礎層
	 * - img-src：允許從 Webview 自身及 HTTPS 來源載入圖片
	 * - style-src：允許 inline styles（Preact SSR 渲染需要）
	 * - script-src：允許 inline scripts 及 eval（Preact/JSX 執行需要）
	 * - connect-src：僅允許向 Webview 自身發起連線
	 *
	 * Directive descriptions:
	 * - default-src 'none': Deny all resources by default, as the strictest base layer
	 * - img-src: Allow loading images from the Webview itself and HTTPS sources
	 * - style-src: Allow inline styles (required by Preact SSR rendering)
	 * - script-src: Allow inline scripts and eval (required by Preact/JSX execution)
	 * - connect-src: Only allow connections to the Webview itself
	 */
	const csp = [
		`default-src 'none'`,
		`img-src ${cspSource} https:`,
		`style-src ${cspSource} 'unsafe-inline'`,
		`script-src ${cspSource} 'unsafe-inline' 'unsafe-eval'`,
		`connect-src ${cspSource}`,
	].join('; ');

	/**
	 * http-equiv 屬性在 Preact JSX 型別定義中不存在，需要忽略型別檢查
	 * http-equiv attribute does not exist in Preact JSX type definitions, type check must be ignored
	 */
	// @ts-ignore
	return <meta http-equiv="Content-Security-Policy" content={csp} />;
}

/** ─── App 根組件 / App root component ─── */

/**
 * Webview SSR 根組件
 * Webview SSR root component
 *
 * 組合所有 SSR 子組件，產生完整的 HTML 文件結構。
 * 在 `<body>` 末尾注入兩個 `<script>` 標籤：
 * 1. `window.__INITIAL_STATE__`：將 Extension host 的狀態橋接至 Webview 前端
 * 2. Webview bundle：載入所有 client-side 互動邏輯
 *
 * Composes all SSR child components to produce the complete HTML document structure.
 * Injects two `<script>` tags at the end of `<body>`:
 * 1. `window.__INITIAL_STATE__`: Bridges Extension host state to the Webview frontend
 * 2. Webview bundle: Loads all client-side interaction logic
 */
export function App({
	availableIDEs,
	unavailableIDEs,
	currentIDEName,
	sourceIDEUuid,
	languageConfig,
	supportedLanguages,
	currentLanguage,
	cssContent,
	cspSource,
	webviewScriptUri,
	initialState,
}: IAppProps)
{
	/**
	 * 將初始狀態序列化為 JSON 字串，用於注入 `window.__INITIAL_STATE__`
	 * Serialize initial state to JSON string for injecting into `window.__INITIAL_STATE__`
	 */
	const initialStateJson = JSON.stringify(initialState);

	return (
		<html lang="en">
			<head>
				{/* 字符編碼設定，確保多語言文字正確顯示 / Character encoding, ensures multilingual text displays correctly */}
				<meta charset="UTF-8" />

				{/* 內容安全策略，限制資源載入來源防止 XSS / Content Security Policy, restricts resource loading sources to prevent XSS */}
				<ContentSecurityPolicy cspSource={cspSource} />

				{/* 響應式視口設定 / Responsive viewport settings */}
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />

				{/* 頁面標題 / Page title */}
				<title>IDE Settings Sync</title>

				{/* 內嵌編譯後的 SCSS 樣式，確保樣式與擴充功能版本一致 / Inline compiled SCSS styles, ensures styles match the extension version */}
				<style>{cssContent}</style>
			</head>
			<body>
				<div class="container">
					{/* 頁面標題列 / Page header */}
					<div class="header">
						<h1>IDE Settings Sync</h1>
					</div>

					{/* IDE 列表區塊：顯示可用與不可用的 IDE / IDE list section: shows available and unavailable IDEs */}
					<IDEListSection
						availableIDEs={availableIDEs}
						unavailableIDEs={unavailableIDEs}
						currentIDEName={currentIDEName}
						sourceIDEUuid={sourceIDEUuid}
					/>

					{/* 語言設定區塊：主語言下拉選單與 Fallback 列表 / Language config section: primary language dropdown and fallback list */}
					<LanguageConfiguration
						languageConfig={languageConfig}
						supportedLanguages={supportedLanguages}
						currentLanguage={currentLanguage}
					/>

					{/* 來源 IDE 指示器：顯示當前選擇的同步來源 IDE / Source IDE indicator: shows the currently selected sync source IDE */}
					<SourceIdeIndicator
						sourceIDEName={currentIDEName}
						sourceIDEUuid={sourceIDEUuid}
					/>

					{/* 設定分頁導覽列 / Settings tab navigation bar */}
					<div class={EnumCssClassSelector.tabs}>
						<SettingsNavigation />
					</div>

					{/* Sync 分頁：搜尋與同步設定 / Sync tab: search and sync settings */}
					<SyncTab />

					{/* Values 分頁：檢視所有 IDE 設定值 / Values tab: view all IDE setting values */}
					<AllSettingsTab />

					{/* Selected 分頁：已儲存的選取設定列表 / Selected tab: saved selected settings list */}
					<SelectedTab />

					{/* Export/Import 分頁：匯出與匯入設定 / Export/Import tab: export and import settings */}
					<div id={EnumTabName.exportImport} class="tab-content">
						<ExportImportPanel importResult={undefined} isProcessing={false} />
					</div>
				</div>

				{/**
				 * 注入初始狀態至 window.__INITIAL_STATE__
				 * Inject initial state into window.__INITIAL_STATE__
				 *
				 * 必須在 Webview bundle script 之前載入，
				 * 確保 bundle 初始化時能立即讀取到狀態。
				 * Must be loaded before the Webview bundle script,
				 * ensuring the bundle can immediately read the state during initialization.
				 */}
				<script dangerouslySetInnerHTML={{ __html: `window.__INITIAL_STATE__ = ${initialStateJson};` }} />

				{/* Webview bundle：載入所有 client-side 互動邏輯 / Webview bundle: loads all client-side interaction logic */}
				<script src={webviewScriptUri}></script>
			</body>
		</html>
	);
}
