/**
 * Webview 前端共用型別定義
 * Webview frontend shared type definitions
 *
 * 此檔案不得 import 任何 VS Code 或 Node.js 相依模組，
 * 確保 Webview bundle 在瀏覽器沙盒中可獨立執行。
 * This file must NOT import any VS Code or Node.js dependent modules,
 * ensuring the Webview bundle can run independently in the browser sandbox.
 */

import { IIDEInfo } from '../../src/types';
import { saveSearchHistory } from './scripts/memory';
import { displayAllSettings, displaySelectedSettingsList, removeFromSelectedSettings, searchSettings } from './scripts/settings';

/** ─── 語言相關型別 / Language-related types ─── */

/**
 * 支援的語言代碼聯合型別
 * Union type of supported language codes
 */
export type ILanguageCode = 'en' | 'zh-tw' | 'zh-cn' | 'ja' | 'de' | 'fr';

/**
 * 語言配置介面（精簡版，不含 VS Code 相依）
 * Language configuration interface (simplified, no VS Code dependency)
 */
export interface ILanguageConfig
{
	/** 主顯示語言 / Primary display language */
	primary: ILanguageCode;
	/** Fallback 語言列表，依序查找直到找到有效描述 / Fallback language list, searched in order until a valid description is found */
	fallbackList: ILanguageCode[];
	/** 副顯示語言（可選）/ Secondary display language (optional) */
	secondary?: ILanguageCode;
	/** 是否在設定描述旁顯示副語言翻譯 / Whether to show secondary language translation alongside setting descriptions */
	showSecondary: boolean;
}

/** ─── IDE 相關型別 / IDE-related types ─── */

/**
 * IDE 資訊介面（用於 Webview 渲染）
 * IDE information interface (for Webview rendering)
 *
 * 精簡版的 IDE 資訊，用於傳遞給前端組件，不含 VS Code 相依。
 * Simplified IDE information for passing to frontend components, without VS Code dependency.
 */
export interface IIDEInfoWebview extends Omit<IIDEInfo, 'settingProvider'>
{
	/** IDE 的所有設定鍵值對 / All setting key-value pairs of the IDE */
	settings: Record<string, any>;
}

/**
 * 不可用的 IDE 資訊介面（用於 Webview 渲染）
 * Unavailable IDE information interface (for Webview rendering)
 *
 * 用於顯示系統中預期存在但實際未偵測到的 IDE。
 * Used to display IDEs that are expected to exist in the system but were not detected.
 */
export interface IUnavailableIDEInfoWebview
{
	/** IDE 顯示名稱 / IDE display name */
	name: string;
	/** IDE 類型 / IDE type */
	type: string;
	/** 預期的設定資料夾路徑（用於顯示未偵測到的原因）/ Expected settings folder path (used to show why it was not detected) */
	expectedPath: string;
	/** 不可用原因說明 / Reason why the IDE is unavailable */
	reason?: string;
}

/** ─── Webview 初始狀態 / Webview initial state ─── */

/**
 * Webview 初始狀態介面
 * Webview initial state interface
 *
 * 由 Extension host 在 SSR 時序列化為 JSON，
 * 透過 `window.__INITIAL_STATE__` 注入至 Webview，
 * 讓前端 bundle 在載入時即可取得所有必要的初始資料。
 *
 * Serialized to JSON by the Extension host during SSR,
 * injected into the Webview via `window.__INITIAL_STATE__`,
 * allowing the frontend bundle to access all necessary initial data on load.
 */
export interface IWebviewState
{
	/** 可用的 IDE 列表（含各 IDE 的設定鍵值對）/ List of available IDEs (including each IDE's setting key-value pairs) */
	ideList: IIDEInfoWebview[];
	/** 當前使用的語言代碼 / Currently active language code */
	currentLanguage: string;
	/** 語言配置物件 / Language configuration object */
	languageConfig: ILanguageConfig;
	/** 當前執行此擴充功能的 IDE 名稱 / Name of the IDE currently running this extension */
	currentIDEName: string;
	/** 當前執行此擴充功能的 IDE UUID / UUID of the IDE currently running this extension */
	currentIDEUuid: string;
	/** 上次儲存的搜尋字串（用於頁面重載後恢復搜尋狀態）/ Last saved search string (for restoring search state after page reload) */
	savedSearchHistory: string;
	/** 使用者已勾選並儲存的設定 key 列表 / List of setting keys checked and saved by the user */
	savedSelectedSettings: string[];
	/** 使用者已勾選的 IDE 索引列表 / List of IDE indices checked by the user */
	savedSelectedIDEs: number[];
	/**
	 * 多語言設定描述對照表（key → { primary, secondary? }）
	 * Multilingual setting description lookup table (key → { primary, secondary? })
	 *
	 * 由 Extension host 根據當前語言配置預先產生，
	 * 避免在 Webview 端重複執行語言查找邏輯。
	 * Pre-generated by the Extension host based on current language config,
	 * avoiding repeated language lookup logic on the Webview side.
	 */
	settingDescriptions: Record<string, { primary: string; secondary?: string }>;

	/** 來源 IDE UUID / Source IDE UUID */
	sourceIDEUuid?: string;
}

/** ─── 匯出/匯入相關型別 / Export/Import related types ─── */

/**
 * 匯入操作的結果介面
 * Import operation result interface
 *
 * 從 src/types.ts 的 IImportResult 複製，去除 VS Code 相依，
 * 確保 Webview bundle 可在瀏覽器沙盒中獨立使用。
 * Copied from IImportResult in src/types.ts, without VS Code dependency,
 * ensuring the Webview bundle can be used independently in the browser sandbox.
 */
export interface IImportResult
{
	/** 匯入是否成功 / Whether the import was successful */
	success: boolean;
	/** 成功匯入的自訂 IDE 數量 / Number of custom IDEs successfully imported */
	importedCustomIDEs: number;
	/** 成功匯入的已選設定數量 / Number of selected settings successfully imported */
	importedSelectedSettings: number;
	/** 跳過的自訂 IDE 數量 / Number of custom IDEs skipped */
	skippedCustomIDEs: number;
	/** 跳過的已選設定數量 / Number of selected settings skipped */
	skippedSelectedSettings: number;
	/** 錯誤訊息列表 / List of error messages */
	errors: string[];
	/** 警告訊息列表 / List of warning messages */
	warnings: string[];
}

/**
 * Webview 窗口接口，用于 TypeScript 类型安全
 * Webview window interface for TypeScript type safety
 */
export type IWebviewWindow = Window & typeof globalThis & {
	__INITIAL_STATE__: IWebviewState;

	displayAllSettings: typeof displayAllSettings;
	searchSettings: typeof searchSettings;
	removeFromSelectedSettings: typeof removeFromSelectedSettings;
	displaySelectedSettingsList: typeof displaySelectedSettingsList;
	saveSearchHistory: typeof saveSearchHistory;
}
