/**
 * Webview 前端共用型別定義
 * Webview frontend shared type definitions
 *
 * 此檔案不得 import 任何 VS Code 或 Node.js 相依模組，
 * 確保 Webview bundle 在瀏覽器沙盒中可獨立執行。
 * This file must NOT import any VS Code or Node.js dependent modules,
 * ensuring the Webview bundle can run independently in the browser sandbox.
 *
 * 凡與 src/types.ts 結構相同的型別，一律直接 re-export，
 * 不在此重複定義，確保單一事實來源。
 * All types structurally identical to src/types.ts are re-exported directly,
 * never redefined here, ensuring a single source of truth.
 */

import {
	IIDEInfoBase,
	IUnavailableIDEBase,
	EnumLanguageCode,
	EnumIDEInfoType,
	ILanguageConfig,
	IImportResult,
} from '../../src/types';

/** ─── Re-export 共用型別 / Re-export shared types ─── */

export { EnumLanguageCode, EnumIDEInfoType, ILanguageConfig, IImportResult };

/** ─── Webview 專用列舉 / Webview-specific enums ─── */

export const enum EnumShowMessageType
{
	SUCCESS = 'success',
	ERROR = 'error',
	INFO = 'info',
	WARNING = 'warning'
}

/** ─── IDE 相關型別 / IDE-related types ─── */

/**
 * IDE 資訊介面（用於 Webview 渲染）
 * IDE information interface (for Webview rendering)
 *
 * 繼承 IIDEInfoBase（可序列化核心），加上 Webview 端需要的 settings 鍵值對。
 * 不含 settingProvider，確保 Webview bundle 在瀏覽器沙盒中可獨立執行。
 *
 * Extends IIDEInfoBase (serializable core), adding the settings key-value pairs needed by the Webview.
 * Excludes settingProvider, ensuring the Webview bundle can run independently in the browser sandbox.
 */
export interface IIDEInfoWebview extends IIDEInfoBase
{
	/** IDE 的所有設定鍵值對 / All setting key-value pairs of the IDE */
	settings: Record<string, any>;
}

/**
 * 不可用的 IDE 資訊介面（用於 Webview 渲染）
 * Unavailable IDE information interface (for Webview rendering)
 *
 * 繼承 IUnavailableIDEBase（共通基底），type 直接使用 EnumIDEInfoType。
 * EnumIDEInfoType 為 const enum，esbuild 編譯時 inline 為字串字面量，
 * 不會在 Webview bundle 中引入任何 VS Code 執行期相依。
 *
 * Extends IUnavailableIDEBase (common base), type uses EnumIDEInfoType directly.
 * EnumIDEInfoType is a const enum; esbuild inlines it as string literals at compile time,
 * introducing no VS Code runtime dependency in the Webview bundle.
 */
export interface IUnavailableIDEInfoWebview extends IUnavailableIDEBase
{
	/** IDE 類型 / IDE type */
	type: EnumIDEInfoType;
}

/** ─── Webview 初始狀態 / Webview initial state ─── */

/**
 * Webview 初始狀態介面
 * Webview initial state interface
 *
 * 由 Extension host 在 SSR 時序列化為 JSON，
 * 透過 `window.__INITIAL_STATE__` 注入至 Webview，
 * 讓前端 bundle 在載入時即可取得所有必要的初始資料。
 *
 * Serialized to JSON by the Extension host during SSR,
 * injected into the Webview via `window.__INITIAL_STATE__`,
 * allowing the frontend bundle to access all necessary initial data on load.
 */
export interface IWebviewState
{
	/** 可用的 IDE 列表（含各 IDE 的設定鍵值對）/ List of available IDEs (including each IDE's setting key-value pairs) */
	ideList: IIDEInfoWebview[];
	/** 當前使用的語言代碼 / Currently active language code */
	currentLanguage: string;
	/** 語言配置物件 / Language configuration object */
	languageConfig: ILanguageConfig;
	/** 當前執行此擴充功能的 IDE 名稱 / Name of the IDE currently running this extension */
	currentIDEName: string;
	/** 當前執行此擴充功能的 IDE UUID / UUID of the IDE currently running this extension */
	currentIDEUuid: string;
	/** 上次儲存的搜尋字串（用於頁面重載後恢復搜尋狀態）/ Last saved search string (for restoring search state after page reload) */
	savedSearchHistory: string;
	/** 使用者已勾選並儲存的設定 key 列表 / List of setting keys checked and saved by the user */
	savedSelectedSettings: string[];
	/** 使用者已勾選的 IDE 索引列表 / List of IDE indices checked by the user */
	savedSelectedIDEs: number[];
	/**
	 * 多語言設定描述對照表（key → { primary, secondary? }）
	 * Multilingual setting description lookup table (key → { primary, secondary? })
	 *
	 * 由 Extension host 根據當前語言配置預先產生，
	 * 避免在 Webview 端重複執行語言查找邏輯。
	 * Pre-generated by the Extension host based on current language config,
	 * avoiding repeated language lookup logic on the Webview side.
	 */
	settingDescriptions: Record<string, { primary: string; secondary?: string }>;
	/** 來源 IDE UUID / Source IDE UUID */
	sourceIDEUuid?: string;
}
