/**
 * 設定顯示與管理模組
 * Settings display and management module
 *
 * 處理設定的搜尋、顯示與管理功能。
 * 邏輯從 settingsSyncPanel.ts 的 inline `<script>` 遷移而來。
 * Handles settings search, display, and management functionality.
 * Logic migrated from the inline `<script>` in settingsSyncPanel.ts.
 */

import { vscode } from '../global/vscode-api';
import { showMessage } from './messages';
import { sourceIDEUuid, checkedSettingKeys, searchQuery } from '../store';
import { EnumWebviewCommand } from '../webviewMessages';
import { EnumShowMessageType, IWebviewState } from '../types';
import type { IWebviewWindow } from '../global/window-this';
import { querySelectorById } from '../utils/elem-get';
import { saveSearchHistory } from './memory';
import { EnumWebviewElemId } from '../types/elem-const';

/**
 * 取得注入的初始狀態物件的便捷存取器
 * Convenience accessor for the injected initial state object
 *
 * 使用 `?? {}` fallback 確保在狀態尚未注入時不會拋出例外。
 * Uses `?? {}` fallback to ensure no exception is thrown when state has not yet been injected.
 */
function getState(): IWebviewState
{
	return (window as any as IWebviewWindow).__INITIAL_STATE__ ?? {};
}

/** ─── 描述查找輔助函數 / Description lookup helpers ─── */

/**
 * 查找設定 key 對應的人類可讀描述字串
 * Look up the human-readable description string for a setting key
 *
 * 描述來自 `__INITIAL_STATE__.settingDescriptions`，
 * 由 Extension host 根據當前語言配置預先產生。
 * 若有副語言描述，會以 `<small>` 標籤附加在主語言描述後。
 *
 * Descriptions come from `__INITIAL_STATE__.settingDescriptions`,
 * pre-generated by the Extension host based on current language config.
 * If a secondary language description exists, it is appended after the primary description in a `<small>` tag.
 *
 * @param key - 點分隔的 VS Code 設定 key / Dot-separated VS Code setting key
 * @returns 包含 HTML 標記的描述字串，找不到時回傳預設文字 / Description string with HTML markup, returns default text if not found
 */
export function getSettingDescription(key: string): string
{
	const descriptions: Record<string, { primary: string; secondary?: string }> =
		getState().settingDescriptions ?? {};
	const desc = descriptions[key];
	if (!desc) return 'No description available';
	/**
	 * 若有副語言描述，以斜體小字附加在主語言描述後
	 * If secondary language description exists, append it after the primary description in italic small text
	 */
	if (desc.secondary)
	{
		return `${desc.primary}<br/><small style="color: #999; font-style: italic;">(${desc.secondary})</small>`;
	}
	return desc.primary || 'No description available';
}

/** ─── 狀態變更輔助函數 / State mutation helpers ─── */

/**
 * 清除搜尋輸入框的文字與搜尋結果
 * Clear the search input text and search results
 *
 * 同時儲存清空後的搜尋字串至 globalState。
 * Also saves the cleared search string to globalState.
 */
export function clearSearch(): void
{
	/**
	 * 更新 searchQuery signal，SearchResultsList 組件自動清空
	 * Update searchQuery signal; SearchResultsList component clears automatically
	 */
	searchQuery.value = '';
	saveSearchHistory();
}

/**
 * 從已儲存的選取設定列表中移除單一設定 key
 * Remove a single setting key from the saved selected settings list
 *
 * @param key - 要移除的點分隔 VS Code 設定 key / Dot-separated VS Code setting key to remove
 */
export function removeFromSelectedSettings(key: string): void
{
	const state = getState();
	const savedSelectedSettings: string[] = state.savedSelectedSettings ?? [];
	const index = savedSelectedSettings.indexOf(key);
	/**
	 * 找到後從陣列中移除，並同步至 Extension host 的 globalState
	 * If found, remove from array and sync to Extension host's globalState
	 */
	if (index > -1)
	{
		savedSelectedSettings.splice(index, 1);
		vscode.postMessage({ command: EnumWebviewCommand.SaveSelectedSettings, selectedSettings: savedSelectedSettings });
		/**
		 * 更新 checkedSettingKeys signal，SelectedSettingsList 組件自動重新渲染
		 * Update checkedSettingKeys signal; SelectedSettingsList component re-renders automatically
		 */
		const next = new Set(checkedSettingKeys.value);
		next.delete(key);
		checkedSettingKeys.value = next;
		showMessage(`✓ Removed "${key}" from selected settings`, EnumShowMessageType.SUCCESS);
	}
}

/**
 * 在使用者確認後清除所有已儲存的選取設定
 * Clear all saved selected settings after user confirmation
 */
export function clearAllSelectedSettings(): void
{
	if (confirm('Clear all selected settings?'))
	{
		const state = getState();
		/**
		 * 清空陣列並同步至 Extension host 的 globalState
		 * Clear the array and sync to Extension host's globalState
		 */
		state.savedSelectedSettings = [];
		vscode.postMessage({ command: EnumWebviewCommand.SaveSelectedSettings, selectedSettings: [] });
		/**
		 * 清空 checkedSettingKeys signal，SelectedSettingsList 組件自動重新渲染
		 * Clear checkedSettingKeys signal; SelectedSettingsList component re-renders automatically
		 */
		checkedSettingKeys.value = new Set();
		showMessage('✓ All selected settings cleared', EnumShowMessageType.SUCCESS);
	}
}

/**
 * 請求 Extension host 重新載入設定資料並重繪 Webview
 * Request the Extension host to reload settings data and redraw the Webview
 */
export function refreshSettings(): void
{
	vscode.postMessage({ command: EnumWebviewCommand.RefreshData });
	showMessage('⟳ Settings refreshed', EnumShowMessageType.INFO);
}
