/**
 * 設定顯示與管理模組
 * Settings display and management module
 *
 * 處理設定的搜尋、顯示與管理功能。
 * 邏輯從 settingsSyncPanel.ts 的 inline `<script>` 遷移而來。
 * Handles settings search, display, and management functionality.
 * Logic migrated from the inline `<script>` in settingsSyncPanel.ts.
 */

import { vscode } from '../global/vscode-api';
import { showMessage } from './messages';
import { sourceIDEUuid, checkedSettingKeys, searchQuery } from '../store';
import { EnumWebviewCommand } from '../webviewMessages';
import { EnumShowMessageType, IWebviewState } from '../types';
import { IWebviewWindow } from '../global/window-types';
import { EnumWebviewElemSelector, queryWebviewElem } from './elem-get';
import { saveSearchHistory } from './memory';

/**
 * 取得注入的初始狀態物件的便捷存取器
 * Convenience accessor for the injected initial state object
 *
 * 使用 `?? {}` fallback 確保在狀態尚未注入時不會拋出例外。
 * Uses `?? {}` fallback to ensure no exception is thrown when state has not yet been injected.
 */
function getState(): IWebviewState
{
	return (window as any as IWebviewWindow).__INITIAL_STATE__ ?? {};
}

/** ─── 描述查找輔助函數 / Description lookup helpers ─── */

/**
 * 查找設定 key 對應的人類可讀描述字串
 * Look up the human-readable description string for a setting key
 *
 * 描述來自 `__INITIAL_STATE__.settingDescriptions`，
 * 由 Extension host 根據當前語言配置預先產生。
 * 若有副語言描述，會以 `<small>` 標籤附加在主語言描述後。
 *
 * Descriptions come from `__INITIAL_STATE__.settingDescriptions`,
 * pre-generated by the Extension host based on current language config.
 * If a secondary language description exists, it is appended after the primary description in a `<small>` tag.
 *
 * @param key - 點分隔的 VS Code 設定 key / Dot-separated VS Code setting key
 * @returns 包含 HTML 標記的描述字串，找不到時回傳預設文字 / Description string with HTML markup, returns default text if not found
 */
export function getSettingDescription(key: string): string
{
	const descriptions: Record<string, { primary: string; secondary?: string }> =
		getState().settingDescriptions ?? {};
	const desc = descriptions[key];
	if (!desc) return 'No description available';
	/**
	 * 若有副語言描述，以斜體小字附加在主語言描述後
	 * If secondary language description exists, append it after the primary description in italic small text
	 */
	if (desc.secondary)
	{
		return `${desc.primary}<br/><small style="color: #999; font-style: italic;">(${desc.secondary})</small>`;
	}
	return desc.primary || 'No description available';
}

/** ─── HTML 產生函數 / HTML generation functions ─── */

/**
 * 產生單一設定列的 HTML 字串
 * Generate the HTML string for a single setting row
 *
 * 每列包含：設定 key 的勾選框與標籤、多語言描述、各 IDE 的設定值。
 * Each row contains: checkbox and label for the setting key, multilingual description, setting values for each IDE.
 *
 * @param key - 點分隔的 VS Code 設定 key / Dot-separated VS Code setting key
 * @param values - IDE UUID（或名稱）→ 設定值的對照表 / Map of IDE UUID (or name) → setting value
 * @param sourceUuid - 當前選擇的來源 IDE UUID（可選）/ UUID of the currently selected source IDE (optional)
 * @param ideRecord - IDE UUID → IDE 資訊物件的對照表（可選，搜尋視圖使用）/ Map of IDE UUID → IDE info object (optional, used in search view)
 * @returns 設定列的 HTML 字串 / HTML string for the setting row
 */
export function createSettingHTML(
	key: string,
	values: Record<string, any>,
	sourceUuid?: string,
	ideRecord?: Record<string, any>,
): string
{
	let valuesHTML = '';

	Object.entries(values).forEach(([ideUuid, value]) =>
	{
		/**
		 * 處理未設定的值（undefined），以特殊樣式顯示
		 * Handle unset values (undefined) with special display style
		 */
		let displayValue: string;
		if (value === undefined)
		{
			displayValue = '<em style="color: #999;">Not set</em>';
		}
		else if (typeof value === 'object')
		{
			displayValue = JSON.stringify(value, null, 2);
		}
		else
		{
			displayValue = String(value);
		}

		/**
		 * 有 ideRecord 時為搜尋視圖（以 UUID 為 key），否則為所有設定視圖（以名稱為 key）
		 * When ideRecord is provided, we are in the search view (UUID-keyed); otherwise in the all-settings view (name-keyed)
		 */
		const ideName: string = ideRecord ? (ideRecord[ideUuid]?.name ?? ideUuid) : ideUuid;
		const currentIDEName: string = getState().currentIDEName ?? '';
		const isCurrent = ideName === currentIDEName;

		/**
		 * 根據值的狀態與是否為當前 IDE 決定 CSS class
		 * Determine CSS class based on value state and whether it is the current IDE
		 */
		let valueClass = value === undefined ? 'ide-value-missing' : '';
		if (!valueClass && isCurrent)
		{
			valueClass = 'current';
		}

		const isSelected = ideUuid === sourceUuid;
		valueClass += isSelected ? ' source-ide' : '';

		valuesHTML += `<div class="ide-value ${valueClass.trim()}">
			<div class="ide-value-label">${ideName}${isSelected ? ' (Selected)' : ''}</div>
			<div class="ide-value-content">${displayValue}</div>
		</div>`;
	});

	const settingId = 'setting-' + key.replace(/\./g, '_');
	const description = getSettingDescription(key);

	return `<div class="setting-item">
		<div class="setting-key">
			<input type="checkbox" class="setting-checkbox" id="${settingId}" data-key="${key}">
			<label for="${settingId}">${key}</label>
		</div>
		<div class="setting-description">${description}</div>
		<div class="setting-values">${valuesHTML}</div>
	</div>`;
}

/** ─── 顯示函數 / Display functions ─── */

/**
 * 將所有已偵測 IDE 的設定值渲染至 `#allSettings` 容器
 * Render all settings from every detected IDE into the `#allSettings` container
 *
 * 處理步驟：
 * 1. 收集所有 IDE 中出現過的唯一設定 key
 * 2. 建立 key → { ideName: value } 的對照表（未設定的值標記為 undefined）
 * 3. 依字母順序排序後逐一渲染
 *
 * Processing steps:
 * 1. Collect all unique setting keys that appear across all IDEs
 * 2. Build a key → { ideName: value } map (unset values marked as undefined)
 * 3. Sort alphabetically and render one by one
 */
export function displayAllSettings(): void
{
	const allSettingsDiv = document.getElementById('allSettings');
	if (!allSettingsDiv) return;
	allSettingsDiv.innerHTML = '';

	const ideList: IWebviewState["ideList"] = getState().ideList ?? [];

	/**
	 * 步驟 1：收集所有 IDE 中出現過的唯一設定 key
	 * Step 1: Collect all unique setting keys across ALL IDEs
	 */
	const allKeys = new Set<string>();
	ideList.forEach(ide =>
	{
		Object.keys(ide.settings || {}).forEach(key => allKeys.add(key));
	});

	/**
	 * 步驟 2：建立 key → { ideName: value } 對照表
	 * Step 2: Build a key → { ideName: value } map for every IDE
	 *
	 * 未設定的值明確標記為 undefined，以便在 UI 中顯示「Not set」。
	 * Unset values are explicitly marked as undefined to display "Not set" in the UI.
	 */
	const settingMap = new Map<string, Record<string, any>>();
	allKeys.forEach(key =>
	{
		settingMap.set(key, {});
		ideList.forEach(ide =>
		{
			if (ide.settings && Object.prototype.hasOwnProperty.call(ide.settings, key))
			{
				settingMap.get(key)![ide.name] = ide.settings[key];
			}
			else
			{
				settingMap.get(key)![ide.name] = undefined;
			}
		});
	});

	/**
	 * 步驟 3：依字母順序排序並渲染
	 * Step 3: Sort alphabetically and render
	 */
	const sortedKeys = Array.from(allKeys).sort();
	sortedKeys.forEach(key =>
	{
		allSettingsDiv.innerHTML += createSettingHTML(key, settingMap.get(key)!);
	});
}

/**
 * 依 `#searchInput` 的當前值搜尋設定，並將符合的結果渲染至 `#searchResults`
 * Search settings by the current value of `#searchInput` and render matching results into `#searchResults`
 *
 * 處理步驟：
 * 1. 收集所有 IDE 中 key 包含搜尋字串的設定
 * 2. 建立 key → { ideUuid: value } 的對照表
 * 3. 依字母順序排序後逐一渲染（含來源 IDE 標記）
 *
 * Processing steps:
 * 1. Collect settings from all IDEs whose key contains the search string
 * 2. Build a key → { ideUuid: value } map
 * 3. Sort alphabetically and render one by one (with source IDE marking)
 */
export function searchSettings(): void
{
	const searchInput = document.getElementById('searchInput') as HTMLInputElement | null;
	const query = searchInput?.value?.toLowerCase() ?? '';
	const resultsDiv = queryWebviewElem<HTMLDivElement>(EnumWebviewElemSelector.searchResults);
	if (!resultsDiv) return;
	resultsDiv.innerHTML = '';

	if (query.length === 0) return;

	const ideList: IWebviewState["ideList"] = getState().ideList ?? [];

	/**
	 * 步驟 1：收集所有 key 包含搜尋字串的唯一設定 key
	 * Step 1: Collect all unique setting keys whose key contains the search string
	 */
	const matchedKeys = new Set<string>();
	ideList.forEach(ide =>
	{
		Object.keys(ide.settings || {}).forEach(key =>
		{
			if (key.toLowerCase().includes(query)) matchedKeys.add(key);
		});
	});

	/**
	 * 步驟 2：建立 key → { ideUuid: value } 對照表與 ideRecord 對照表
	 * Step 2: Build key → { ideUuid: value } map and ideRecord map
	 *
	 * ideRecord 用於在 createSettingHTML 中查找 IDE 名稱。
	 * ideRecord is used to look up IDE names in createSettingHTML.
	 */
	const ideRecord: Record<string, any> = {};
	const settingMap = new Map<string, Record<string, any>>();

	matchedKeys.forEach(key =>
	{
		settingMap.set(key, {});
		ideList.forEach(ide =>
		{
			ideRecord[ide.uuid] = ide;
			if (ide.settings && Object.prototype.hasOwnProperty.call(ide.settings, key))
			{
				settingMap.get(key)![ide.uuid] = ide.settings[key];
			}
			else
			{
				settingMap.get(key)![ide.uuid] = undefined;
			}
		});
	});

	/**
	 * 從 signal 取得當前選擇的來源 IDE UUID，用於在結果中標記來源 IDE
	 * 比從 DOM 查詢 radio 更可靠：signal 在 handleSourceIDEChange 時即時更新，
	 * 不依賴 DOM 狀態，也不會因為 radio 尚未渲染而取不到值。
	 * Get the currently selected source IDE UUID from signal, used to mark the source IDE in results.
	 * More reliable than querying the radio from DOM: signal is updated immediately in handleSourceIDEChange,
	 * does not depend on DOM state, and won't fail if the radio hasn't rendered yet.
	 */
	const currentSourceUuid = sourceIDEUuid.value;

	/**
	 * 步驟 3：依字母順序排序並渲染
	 * Step 3: Sort alphabetically and render
	 */
	const sortedKeys = Array.from(matchedKeys).sort();
	sortedKeys.forEach(key =>
	{
		resultsDiv.innerHTML += createSettingHTML(key, settingMap.get(key)!, currentSourceUuid, ideRecord);
	});
}

/**
 * 將已儲存的選取設定列表渲染至 `#selectedSettingsList` 容器
 * Render the saved selected settings list into the `#selectedSettingsList` container
 *
 * 若無已選設定，顯示提示文字。
 * 每個設定列包含移除按鈕，可從列表中移除單一項目。
 * If no settings are selected, display a hint text.
 * Each setting row includes a remove button to remove a single item from the list.
 */
export function displaySelectedSettingsList(): void
{
	const selectedListDiv = document.getElementById('selectedSettingsList');
	if (!selectedListDiv) return;
	selectedListDiv.innerHTML = '';

	const state = getState();
	const savedSelectedSettings: string[] = state.savedSelectedSettings ?? [];
	const ideList: IWebviewState["ideList"] = state.ideList ?? [];
	const currentIDEName: string = state.currentIDEName ?? '';

	/**
	 * 無已選設定時顯示提示文字
	 * Show hint text when no settings are selected
	 */
	if (savedSelectedSettings.length === 0)
	{
		selectedListDiv.innerHTML =
			'<div style="color: var(--vscode-descriptionForeground); padding: 20px; text-align: center;">No settings selected yet</div>';
		return;
	}

	/**
	 * 依字母順序排序以確保顯示一致性
	 * Sort alphabetically for consistent display
	 */
	const sortedSelectedSettings = [...savedSelectedSettings].sort();

	sortedSelectedSettings.forEach(key =>
	{
		const description = getSettingDescription(key);
		const settingId = 'setting-' + key.replace(/\./g, '_');

		let valuesHTML = '';

		/**
		 * 遍歷所有 IDE，找出有此設定 key 的 IDE 並渲染其值
		 * Iterate all IDEs, find those with this setting key and render their values
		 */
		ideList.forEach(ide =>
		{
			if (ide.settings && Object.prototype.hasOwnProperty.call(ide.settings, key))
			{
				const value = ide.settings[key];

				let displayValue: string;
				if (value === undefined)
				{
					displayValue = '<em style="color: #999;">Not set</em>';
				}
				else if (typeof value === 'object')
				{
					displayValue = JSON.stringify(value, null, 2);
				}
				else
				{
					displayValue = String(value);
				}

				const isCurrent = ide.name === currentIDEName;
				let valueClass = value === undefined ? 'ide-value-missing' : '';
				if (!valueClass && isCurrent) valueClass = 'current';

				valuesHTML += `<div class="ide-value ${valueClass}">
					<div class="ide-value-label">${ide.name}</div>
					<div class="ide-value-content">${displayValue}</div>
				</div>`;
			}
		});

		selectedListDiv.innerHTML += `<div class="setting-item">
			<div class="setting-key">
				<input type="checkbox" class="setting-checkbox" id="${settingId}" data-key="${key}" checked>
				<label for="${settingId}">${key}</label>
				<button class="btn btn-small" onclick="removeFromSelectedSettings('${key}')" style="margin-left: auto;">✕ Remove</button>
			</div>
			<div class="setting-description">${description}</div>
			<div class="setting-values">${valuesHTML}</div>
		</div>`;
	});
}

/** ─── 狀態變更輔助函數 / State mutation helpers ─── */

/**
 * 清除搜尋輸入框的文字與搜尋結果
 * Clear the search input text and search results
 *
 * 同時儲存清空後的搜尋字串至 globalState。
 * Also saves the cleared search string to globalState.
 */
export function clearSearch(): void
{
	/**
	 * 更新 searchQuery signal，SearchResultsList 組件自動清空
	 * Update searchQuery signal; SearchResultsList component clears automatically
	 */
	searchQuery.value = '';
	saveSearchHistory();
}

/**
 * 從已儲存的選取設定列表中移除單一設定 key
 * Remove a single setting key from the saved selected settings list
 *
 * @param key - 要移除的點分隔 VS Code 設定 key / Dot-separated VS Code setting key to remove
 */
export function removeFromSelectedSettings(key: string): void
{
	const state = getState();
	const savedSelectedSettings: string[] = state.savedSelectedSettings ?? [];
	const index = savedSelectedSettings.indexOf(key);
	/**
	 * 找到後從陣列中移除，並同步至 Extension host 的 globalState
	 * If found, remove from array and sync to Extension host's globalState
	 */
	if (index > -1)
	{
		savedSelectedSettings.splice(index, 1);
		vscode.postMessage({ command: EnumWebviewCommand.SaveSelectedSettings, selectedSettings: savedSelectedSettings });
		/**
		 * 更新 checkedSettingKeys signal，SelectedSettingsList 組件自動重新渲染
		 * Update checkedSettingKeys signal; SelectedSettingsList component re-renders automatically
		 */
		const next = new Set(checkedSettingKeys.value);
		next.delete(key);
		checkedSettingKeys.value = next;
		showMessage(`✓ Removed "${key}" from selected settings`, EnumShowMessageType.SUCCESS);
	}
}

/**
 * 在使用者確認後清除所有已儲存的選取設定
 * Clear all saved selected settings after user confirmation
 */
export function clearAllSelectedSettings(): void
{
	if (confirm('Clear all selected settings?'))
	{
		const state = getState();
		/**
		 * 清空陣列並同步至 Extension host 的 globalState
		 * Clear the array and sync to Extension host's globalState
		 */
		state.savedSelectedSettings = [];
		vscode.postMessage({ command: EnumWebviewCommand.SaveSelectedSettings, selectedSettings: [] });
		/**
		 * 清空 checkedSettingKeys signal，SelectedSettingsList 組件自動重新渲染
		 * Clear checkedSettingKeys signal; SelectedSettingsList component re-renders automatically
		 */
		checkedSettingKeys.value = new Set();
		showMessage('✓ All selected settings cleared', EnumShowMessageType.SUCCESS);
	}
}

/**
 * 請求 Extension host 重新載入設定資料並重繪 Webview
 * Request the Extension host to reload settings data and redraw the Webview
 */
export function refreshSettings(): void
{
	vscode.postMessage({ command: EnumWebviewCommand.RefreshData });
	showMessage('⟳ Settings refreshed', EnumShowMessageType.INFO);
}
