/**
 * 設定顯示與管理模組
 * Settings display and management module
 *
 * 處理設定的搜尋、顯示與管理功能。
 * 邏輯從 settingsSyncPanel.ts 的 inline `<script>` 遷移而來。
 * Handles settings search, display, and management functionality.
 * Logic migrated from the inline `<script>` in settingsSyncPanel.ts.
 */

import { vscode } from '../global/vscode-api';
import { showMessage } from './messages';
import { sourceIDEUuid, checkedSettingKeys, searchQuery } from '../store';
import { EnumWebviewCommand } from '../webviewMessages';
import { EnumShowMessageType, IWebviewState } from '../types';
import type { IWebviewWindow } from '../global/window-this';
import { querySelectorById } from '../utils/elem-get';
import { saveSearchHistory } from './memory';
import { EnumWebviewElemId } from '../types/elem-const';

/**
 * 取得注入的初始狀態物件的便捷存取器
 * Convenience accessor for the injected initial state object
 *
 * 使用 `?? {}` fallback 確保在狀態尚未注入時不會拋出例外。
 * Uses `?? {}` fallback to ensure no exception is thrown when state has not yet been injected.
 *
 * 為什麼需要此函數：初始狀態由 Extension host 透過 SSR 注入至 window 物件，
 * 提供統一的存取點避免重複的型別斷言與 null 檢查。
 * Why this function is needed: Initial state is injected to window object by Extension host via SSR,
 * provides unified access point to avoid repetitive type assertions and null checks.
 */
function getState(): IWebviewState
{
	return (window as any as IWebviewWindow).__INITIAL_STATE__ ?? {};
}

/** ─── 描述查找輔助函數 / Description lookup helpers ─── */

/**
 * 查找設定 key 對應的人類可讀描述字串
 * Look up the human-readable description string for a setting key
 *
 * 描述來自 `__INITIAL_STATE__.settingDescriptions`，
 * 由 Extension host 根據當前語言配置預先產生。
 * 若有副語言描述，會以 `<small>` 標籤附加在主語言描述後。
 *
 * Descriptions come from `__INITIAL_STATE__.settingDescriptions`,
 * pre-generated by the Extension host based on current language config.
 * If a secondary language description exists, it is appended after the primary description in a `<small>` tag.
 *
 * 為什麼描述由 Extension host 預先產生：
 * 設定描述需要根據當前語言動態取得，在 Node.js 端處理更有效率，
 * 避免在前端動態載入大量語言檔案。
 * Why descriptions are pre-generated by Extension host:
 * Setting descriptions need to be dynamically fetched based on current language,
 * processing on Node.js side is more efficient, avoiding loading large language files on frontend.
 *
 * @param key - 點分隔的 VS Code 設定 key / Dot-separated VS Code setting key
 * @returns 包含 HTML 標記的描述字串，找不到時回傳預設文字 / Description string with HTML markup, returns default text if not found
 */
export function getSettingDescription(key: string): string
{
	/**
	 * 從全局狀態中取得設定描述對照表
	 * Get setting description mapping from global state
	 *
	 * 為什麼使用 ?? {} fallback：確保在狀態尚未注入時不會拋出型別錯誤
	 * Why use ?? {} fallback: Ensures no type errors when state hasn't been injected yet
	 */
	const descriptions: Record<string, { primary: string; secondary?: string }> =
		getState().settingDescriptions ?? {};
	const desc = descriptions[key];
	/**
	 * 找不到描述時回傳預設文字
	 * Return default text when description not found
	 *
	 * 為什麼需要 fallback：部分設定可能沒有描述，不應該顯示空白或拋出錯誤
	 * Why fallback needed: Some settings may not have descriptions, shouldn't show blank or throw errors
	 */
	if (!desc) return 'No description available';
	/**
	 * 若有副語言描述，以斜體小字附加在主語言描述後
	 * If secondary language description exists, append it after the primary description in italic small text
	 *
	 * 為什麼使用 <small> 標籤：副語言描述作為補充資訊，視覺上應該較不突顯
	 * Why use <small> tag: Secondary language description is supplementary info, visually less prominent
	 */
	if (desc.secondary)
	{
		return `${desc.primary}<br/><small style="color: #999; font-style: italic;">(${desc.secondary})</small>`;
	}
	return desc.primary || 'No description available';
}

/** ─── 狀態變更輔助函數 / State mutation helpers ─── */

/**
 * 清除搜尋輸入框的文字與搜尋結果
 * Clear the search input text and search results
 *
 * 同時儲存清空後的搜尋字串至 globalState。
 * Also saves the cleared search string to globalState.
 */
export function clearSearch(): void
{
	/**
	 * 更新 searchQuery signal，SearchResultsList 組件自動清空
	 * Update searchQuery signal; SearchResultsList component clears automatically
	 *
	 * 為什麼要保存到歷史：清除搜尋後需要記錄這次操作，以便後續可以恢復或追蹤使用模式
	 * Why save to history: After clearing search, need to record this operation for recovery or usage pattern tracking
	 */
	searchQuery.value = '';
	saveSearchHistory();
}

/**
 * 從已儲存的選取設定列表中移除單一設定 key
 * Remove a single setting key from the saved selected settings list
 *
 * @param key - 要移除的點分隔 VS Code 設定 key / Dot-separated VS Code setting key to remove
 */
export function removeFromSelectedSettings(key: string): void
{
	const state = getState();
	/**
	 * 從全局狀態取得已儲存的選取設定列表
	 * Get saved selected settings list from global state
	 *
	 * 為什麼從 state 讀取而非 signal：這是持久化儲存，需要同步到 Extension host
	 * Why read from state instead of signal: This is persisted storage, needs sync to Extension host
	 */
	const savedSelectedSettings: string[] = state.savedSelectedSettings ?? [];
	const index = savedSelectedSettings.indexOf(key);
	/**
	 * 找到後從陣列中移除，並同步至 Extension host 的 globalState
	 * If found, remove from array and sync to Extension host's globalState
	 *
	 * 為什麼要同步兩個地方：savedSelectedSettings 是持久化儲存，checkedSettingKeys 是響應式狀態
	 * 兩者需要保持一致，否則UI顯示和實際儲存會不符
	 * Why sync two places: savedSelectedSettings is persisted storage, checkedSettingKeys is reactive state
	 * Both need to stay consistent, otherwise UI display and actual storage will mismatch
	 */
	if (index > -1)
	{
		savedSelectedSettings.splice(index, 1);
		vscode.postMessage({ command: EnumWebviewCommand.SaveSelectedSettings, selectedSettings: savedSelectedSettings });
		/**
		 * 更新 checkedSettingKeys signal，SelectedSettingsList 組件自動重新渲染
		 * Update checkedSettingKeys signal; SelectedSettingsList component re-renders automatically
		 *
		 * 為什麼要更新 signal：確保UI立即反映變更，而不需要等待Extension host的回應
		 * Why update signal: Ensure UI reflects changes immediately without waiting for Extension host response
		 */
		const next = new Set(checkedSettingKeys.value);
		next.delete(key);
		checkedSettingKeys.value = next;
		showMessage(`✓ Removed "${key}" from selected settings`, EnumShowMessageType.SUCCESS);
	}
}

/**
 * 在使用者確認後清除所有已儲存的選取設定
 * Clear all saved selected settings after user confirmation
 */
export function clearAllSelectedSettings(): void
{
	/**
	 * 請求使用者確認是否清除所有選取設定
	 * Request user confirmation before clearing all selected settings
	 *
	 * 為什麼需要確認：清除所有選取設定是破壞性操作，需要防止誤操作
	 * Why confirmation needed: Clearing all selected settings is destructive, prevents accidental operations
	 */
	if (confirm('Clear all selected settings?'))
	{
		const state = getState();
		/**
		 * 清空陣列並同步至 Extension host 的 globalState
		 * Clear the array and sync to Extension host's globalState
		 *
		 * 為什麼要同時更新兩處：確保持久化儲存和記憶體狀態都清空
		 * Why update both places: Ensure both persisted storage and in-memory state are cleared
		 */
		state.savedSelectedSettings = [];
		vscode.postMessage({ command: EnumWebviewCommand.SaveSelectedSettings, selectedSettings: [] });
		/**
		 * 清空 checkedSettingKeys signal，SelectedSettingsList 組件自動重新渲染
		 * Clear checkedSettingKeys signal; SelectedSettingsList component re-renders automatically
		 *
		 * 為什麼要清空 signal：確保UI立即清空，提供即時反饋
		 * Why clear signal: Ensure UI clears immediately, providing instant feedback
		 */
		checkedSettingKeys.value = new Set();
		showMessage('✓ All selected settings cleared', EnumShowMessageType.SUCCESS);
	}
}

/**
 * 請求 Extension host 重新載入設定資料並重繪 Webview
 * Request the Extension host to reload settings data and redraw the Webview
 *
 * 為什麼需要重新載入：設定可能在其他 IDE 中被修改，需要獲取最新狀態
 * 重新載入會從 Extension host 重新取得所有設定並重新渲染整個 Webview
 * Why reload needed: Settings may be modified in other IDEs, need to get latest state
 * Reloading fetches all settings from Extension host and re-renders entire Webview
 */
export function refreshSettings(): void
{
	vscode.postMessage({ command: EnumWebviewCommand.RefreshData });
	showMessage('⟳ Settings refreshed', EnumShowMessageType.INFO);
}
